<a href="https://colab.research.google.com/github/DHANYAVARSHINI/Bootstrap_website/blob/master/numpy_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Defining 1D array
my1DArray = np.array([1, 8, 27, 64])
print(my1DArray)


[ 1  8 27 64]


In [ ]:
# Defining and printing 2D array
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print(my2DArray)

[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]


In [ ]:
#Defining and printing 3D array
my3DArray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7 ,8]], [[ 1, 2, 3,
4],[ 9, 10, 11, 12]]])
print(my3DArray)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [ ]:
# Print out memory address
print(my2DArray.data)


In [ ]:
# Print the shape of array
print(my2DArray.shape)


(3, 4)


In [ ]:
# Print out the data type of the array
print(my2DArray.dtype)

int64


In [ ]:
# Print the stride of the array.
print(my2DArray.strides)

(32, 8)


In [ ]:
# Array of ones
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Array of zeros
zeros = np.zeros((2,3,4),dtype=np.int16)
#zeros = np.zeros((2,3,4))
print(zeros)


[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
# Array with random values
np.random.random((2,2))

array([[0.10027481, 0.23524963],
       [0.88614494, 0.34473928]])

In [ ]:
# Empty array
emptyArray = np.empty((3,2))
print(emptyArray)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Full array
fullArray = np.full((2,2),7)
print(fullArray)

[[7 7]
 [7 7]]


In [ ]:
# Array of evenly-spaced values
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

[10 15 20]


In [ ]:
# Array of evenly-spaced values
evenSpacedArray2 = np.linspace(0,2,9)
print(evenSpacedArray2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# Save a numpy array into file
x = np.arange(0.0,50.0,2.0)
np.savetxt('data.out', x, delimiter=',')
# Loading numpy array from text
z = np.loadtxt('data.out', unpack=True)
print(z)


[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48.]


In [ ]:
mydf=np.shape(my2DArray)
print(mydf)

(3, 4)


In [ ]:
# Loading numpy array using genfromtxt method
my_array2 = np.genfromtxt('data.out', skip_header=1, filling_values=-999)
print(my_array2)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36.
 38. 40. 42. 44. 46. 48.]


In [ ]:
# Print the number of `my2DArray`'s dimensions
print(my2DArray.ndim)

2


In [ ]:
# Print the number of `my2DArray`'s elements
print(my2DArray.size)

12
