In [9]:
import numpy as np
# Defining 1D array
my1DArray = np.array([1, 8, 27, 64])
print(my1DArray)


[ 1  8 27 64]


In [10]:
# Defining and printing 2D array
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print(my2DArray)

[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]


In [11]:
#Defining and printing 3D array
my3DArray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7 ,8]], [[ 1, 2, 3,
4],[ 9, 10, 11, 12]]])
print(my3DArray)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [ ]:
# Print out memory address
print(my2DArray.data)


In [ ]:
# Print the shape of array
print(my2DArray.shape)


(3, 4)


In [ ]:
# Print out the data type of the array
print(my2DArray.dtype)

int64


In [ ]:
# Print the stride of the array.
print(my2DArray.strides)

(32, 8)


In [ ]:
# Array of ones
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Array of zeros
zeros = np.zeros((2,3,4),dtype=np.int16)
#zeros = np.zeros((2,3,4))
print(zeros)


[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
# Array with random values
np.random.random((2,2))

array([[0.10027481, 0.23524963],
       [0.88614494, 0.34473928]])

In [ ]:
# Empty array
emptyArray = np.empty((3,2))
print(emptyArray)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Full array
fullArray = np.full((2,2),7)
print(fullArray)

[[7 7]
 [7 7]]


In [ ]:
# Array of evenly-spaced values
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

[10 15 20]


In [ ]:
# Array of evenly-spaced values
evenSpacedArray2 = np.linspace(0,2,9)
print(evenSpacedArray2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# Save a numpy array into file
x = np.arange(0.0,50.0,2.0)
np.savetxt('data.out', x, delimiter=',')
# Loading numpy array from text
z = np.loadtxt('data.out', unpack=True)
print(z)


[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48.]


In [ ]:
mydf=np.shape(my2DArray)
print(mydf)

(3, 4)


In [ ]:
# Loading numpy array using genfromtxt method
my_array2 = np.genfromtxt('data.out', skip_header=1, filling_values=-999)
print(my_array2)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36.
 38. 40. 42. 44. 46. 48.]


In [ ]:
# Print the number of `my2DArray`'s dimensions
print(my2DArray.ndim)

2


In [ ]:
# Print the number of `my2DArray`'s elements
print(my2DArray.size)

12


In [13]:
# Print information about my2DArray's memory layout
print(my2DArray.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [14]:
# Print the length of one array element in bytes
print(my2DArray.itemsize)

8


In [15]:
# Print the total consumed bytes by `my2DArray`'s elements
print(my2DArray.nbytes)


96


In [16]:
  # Rule 1: Two dimensions are operatable if they are equal
  # Create an array of two dimension
  A = np.ones((6, 8))
  # Shape of A  print(A.shape)
  # Create another array
  B = np.random.random((6,8))
  # Shape of B  print(B.shape)
  # Sum of A and B, here the shape of both the matrix is same.
  print(A + B)


[[1.23018865 1.45111181 1.13696546 1.47576772 1.53566665 1.56112676
  1.88314238 1.91084443]
 [1.89608418 1.15610765 1.01649346 1.49947122 1.36428714 1.14034773
  1.90696446 1.13206531]
 [1.61391497 1.74948737 1.20130967 1.69905083 1.1602423  1.8147703
  1.57885306 1.72974506]
 [1.74298221 1.29917047 1.07887836 1.56768965 1.93678389 1.49952694
  1.2644858  1.83695305]
 [1.37748295 1.25435534 1.81183476 1.01454369 1.51010851 1.22548225
  1.10981035 1.9414205 ]
 [1.13041788 1.94939416 1.62066612 1.58364479 1.72139834 1.43208808
  1.6743646  1.57002645]]


In [20]:
# Rule 2: Two dimensions are also compatible when one of them is 1
# Initialize `x`
x = np.ones((3,4))
print(x)
# Check shape of `x`
print(x.shape)
# Initialize `y`
y = np.arange(4)
#Check shape of `y`
print(y.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
(4,)


In [21]:
# Rule 3: Arrays can be broadcast together if they are compatible in all dimensions
x = np.ones((6,8))
y = np.random.random((10, 1, 8))
print(x + y)

[[[1.64488027 1.5044402  1.22083835 1.11497332 1.37389685 1.54064442
   1.83855606 1.2175503 ]
  [1.64488027 1.5044402  1.22083835 1.11497332 1.37389685 1.54064442
   1.83855606 1.2175503 ]
  [1.64488027 1.5044402  1.22083835 1.11497332 1.37389685 1.54064442
   1.83855606 1.2175503 ]
  [1.64488027 1.5044402  1.22083835 1.11497332 1.37389685 1.54064442
   1.83855606 1.2175503 ]
  [1.64488027 1.5044402  1.22083835 1.11497332 1.37389685 1.54064442
   1.83855606 1.2175503 ]
  [1.64488027 1.5044402  1.22083835 1.11497332 1.37389685 1.54064442
   1.83855606 1.2175503 ]]

 [[1.03392971 1.83046362 1.07721872 1.82168636 1.03852821 1.15793602
   1.91387938 1.48272547]
  [1.03392971 1.83046362 1.07721872 1.82168636 1.03852821 1.15793602
   1.91387938 1.48272547]
  [1.03392971 1.83046362 1.07721872 1.82168636 1.03852821 1.15793602
   1.91387938 1.48272547]
  [1.03392971 1.83046362 1.07721872 1.82168636 1.03852821 1.15793602
   1.91387938 1.48272547]
  [1.03392971 1.83046362 1.07721872 1.82168636 1

In [23]:
# Basic operations (+, -, *, /, %)
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 4, 9], [2, 3, -2]])
# Add two array
add = np.add(x, y)
print(add)
# Subtract two array
sub = np.subtract(x, y)
print(sub)
# Multiply two array
mul = np.multiply(x, y)
print(mul)
# Divide x, y
div = np.divide(x,y)
print(div)
# Calculated the remainder of x and y
rem = np.remainder(x, y)
print(rem)


[[ 2  6 12]
 [ 4  6  2]]
[[ 0 -2 -6]
 [ 0  0  6]]
[[ 1  8 27]
 [ 4  9 -8]]
[[ 1.          0.5         0.33333333]
 [ 1.          1.         -2.        ]]
[[0 2 3]
 [0 0 0]]


In [25]:
x = np.array([10, 20, 30, 40, 50])
# Select items at index 0 and 1
print(x[0:2])
# Select item at row 0 and 1 and column 1 from 2D array
y = np.array([[ 1, 2, 3, 4], [ 9, 10, 11 ,12]])
print(y[0:2, 1])
# Specifying conditions
biggerThan2 = (y >= 2)
print(y[biggerThan2])


[10 20]
[ 2 10]
[ 2  3  4  9 10 11 12]
